anguage: objective-c
env:
  matrix:
    - TEST_SDK=iphonesimulator11.4 OS=11.4 NAME='iPhone X'
    - TEST_SDK=iphonesimulator11.4 OS=11.4 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project SwiftyLib.xcodeproj -scheme SwiftyLib -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES

after_success:
 - bash <(curl -s https://codecov.io/bash) -t {1346510f-46da-45c5-bbb4-e3c3be475579}
