language: objective-c

osx_image: xcode12.4
env:
  matrix:
    - TEST_SDK=iphonesimulator14.4 OS=14.4 NAME='iPhone 12'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project SwiftyLib.xcodeproj -scheme SwiftyLib -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES

after_success:
  - bash <(curl -s https://codecov.io/bash) -t {5c8f6a62-7448-4f08-b932-5dcb00358f77}
